### PR TITLE
Minimap transparent color fix

### LINKED ISSUE #340: Minimap renders improperly
One can see through black parts of minimap, because the full black=0 is transparent color key. Try to switch to the other similar color

### PR DESCRIPTION
**Pull request by lpenguin**
closes #340 

Substitute every full black pixel (color=0) on minimap image with color=1.

### CODE REVIEW

File: src/actint/actint.cpp [hunk 1]
```diff
@@ -3989,6 +3989,12 @@ void actIntDispatcher::init(void)
 	if(wMap -> world_ids[CurrentWorld] != -1 && map_names[wMap -> world_ids[CurrentWorld]]){
 		mapObj -> free();
 		mapObj -> load(map_names[wMap -> world_ids[CurrentWorld]],1);
+		int size = mapObj->Size * mapObj->SizeX * mapObj->SizeY;
```
Comment (lpenguin) [inline src/actint/actint.cpp:3992]: TODO: leave a comment why do we need to change world map image

**Comment by stalkerg** [comment]
I suppose we can merge it but not forget to remove it if we find a better solution.

**Comment by lpenguin** [comment]
@stalkerg ready for merging
